<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Show only the files that a developer needs in Solution Explorer. -->
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Bridge.cs" />
    <None Include="ts\src\**\*.ts" />
    <None Include="ts\package.json;ts\tsconfig.json;config.json;README.md" />
    <PackageReference Include="TypescriptBridge.Build" Version="1.0.5" />
  </ItemGroup>

</Project>
