// Auto-generated by TypescriptBridge. Do not edit.
//
// Declares BUILD_MODE as a global compile-time constant so that the
// TypeScript language service in IDEs (Visual Studio, VS Code) can
// resolve references to it without errors.
//
// The actual value is injected by the TypescriptBridge tool during the
// build via esbuild's --define flag. In Debug builds it is "DEBUG";
// in Release builds it is "RELEASE".

declare const BUILD_MODE: string;
