using TypescriptBridge.Tool;

namespace TypescriptBridge.IntegrationTests;

// Tests for CSharpGenerator, which turns two JavaScript payloads
// (debug and release) into a C# static class containing a single
// raw string field whose value is selected via #if DEBUG / #else.
public sealed class CSharpGeneratorTests
{
    // The default output configuration used in most tests.
    private static readonly OutputConfig DefaultOutput = new();

    // The two sample payloads used throughout the tests.
    private const string DebugJs = "console.log(\"debug\");";
    private const string ReleaseJs = "console.log(\"release\");";

    // Each application source gets its own Debug/Release C# field.
    [Fact]
    public void Generate_CreatesIndependentFieldsForNamedEntrypoints()
    {
        var result = CSharpGenerator.Generate(new[]
        {
            new GeneratedBundle("MainCode", "main debug", "main release"),
            new GeneratedBundle("ChartCode", "chart debug", "chart release"),
        }, DefaultOutput, "MyApp");

        Assert.Contains("public static readonly string MainCode =", result);
        Assert.Contains("public static readonly string ChartCode =", result);
        Assert.Contains("main debug", result);
        Assert.Contains("chart release", result);
        Assert.Equal(2, result.Split("#if DEBUG").Length - 1);
    }

    // Verifies that C# consumers can import the generated project namespace.
    [Fact]
    public void Generate_UsesProjectNamespaceWhenProvided()
    {
        var result = CSharpGenerator.Generate(
            DebugJs,
            ReleaseJs,
            DefaultOutput,
            "MyApp.Scripts");

        Assert.Contains("namespace MyApp.Scripts;\n\npublic static class TypescriptProvider", result);
    }

    // Verifies that the generated class and field names appear in the output.
    [Fact]
    public void Generate_UsesConfiguredClassNameAndFieldName()
    {
        var output = new OutputConfig
        {
            ClassName = "MyProvider",
            FieldName = "MyCode",
        };

        var result = CSharpGenerator.Generate(DebugJs, ReleaseJs, output);

        Assert.Contains("public static class MyProvider", result);
        Assert.Contains("public static readonly string MyCode =", result);
    }

    // Verifies that the auto-generated header is present.
    [Fact]
    public void Generate_EmitsAutoGeneratedHeader()
    {
        var result = CSharpGenerator.Generate(DebugJs, ReleaseJs, DefaultOutput);

        Assert.Contains("// <auto-generated />", result);
        Assert.Contains("// This file is generated by TypescriptBridge.", result);
        Assert.Contains("// Do not edit manually.", result);
    }

    // Verifies that the #if DEBUG / #else / #endif block is present.
    [Fact]
    public void Generate_EmitsDebugPreprocessorBlock()
    {
        var result = CSharpGenerator.Generate(DebugJs, ReleaseJs, DefaultOutput);

        Assert.Contains("#if DEBUG", result);
        Assert.Contains("#else", result);
        Assert.Contains("#endif", result);
    }

    // Verifies that both payloads appear in the output.
    [Fact]
    public void Generate_IncludesBothPayloads()
    {
        var result = CSharpGenerator.Generate(DebugJs, ReleaseJs, DefaultOutput);

        Assert.Contains(DebugJs, result);
        Assert.Contains(ReleaseJs, result);
    }

    // Verifies that the debug payload appears before #else.
    [Fact]
    public void Generate_DebugPayloadAppearsBeforeElse()
    {
        var result = CSharpGenerator.Generate(DebugJs, ReleaseJs, DefaultOutput);

        var debugIndex = result.IndexOf(DebugJs, StringComparison.Ordinal);
        var elseIndex = result.IndexOf("#else", StringComparison.Ordinal);
        var releaseIndex = result.IndexOf(ReleaseJs, StringComparison.Ordinal);
        var endifIndex = result.IndexOf("#endif", StringComparison.Ordinal);

        Assert.True(debugIndex < elseIndex);
        Assert.True(elseIndex < releaseIndex);
        Assert.True(releaseIndex < endifIndex);
    }

    // Verifies that a payload containing triple quotes upgrades the
    // raw string literal delimiter to four quotes.
    [Fact]
    public void Generate_HandlesTripleQuoteInJavaScript()
    {
        var debugJs = "let x = \"\"\"end\";";
        var releaseJs = "let y = 1;";

        var result = CSharpGenerator.Generate(debugJs, releaseJs, DefaultOutput);

        Assert.Contains("\"\"\"\"", result);
        Assert.Contains(debugJs, result);
    }

    // Verifies that a payload containing a long run of quotes upgrades the
    // raw string literal delimiter beyond that run.
    [Fact]
    public void Generate_HandlesLongQuoteRun()
    {
        var debugJs = "let x = \"\"\"\"\"\";";
        var releaseJs = "let y = 1;";

        var result = CSharpGenerator.Generate(debugJs, releaseJs, DefaultOutput);

        Assert.Contains(new string('"', 6), result);
        Assert.Contains(debugJs, result);
    }

    // Verifies that two empty payloads still produce a valid class.
    [Fact]
    public void Generate_HandlesEmptyJavaScript()
    {
        var result = CSharpGenerator.Generate(
            string.Empty,
            string.Empty,
            DefaultOutput);

        Assert.Contains("public static class TypescriptProvider", result);
        Assert.Contains("public static readonly string TypescriptCode =", result);
        Assert.Contains("#if DEBUG", result);
        Assert.Contains("#else", result);
        Assert.Contains("#endif", result);
    }

    // Verifies that CRLF line endings in the payloads are normalized to LF.
    [Fact]
    public void Generate_NormalizesCrlfToLf()
    {
        var debugJs = "line1\r\nline2\r\nline3";
        var releaseJs = "line4\r\nline5\r\nline6";

        var result = CSharpGenerator.Generate(debugJs, releaseJs, DefaultOutput);

        Assert.DoesNotContain("\r", result);
        Assert.Contains("line1", result);
        Assert.Contains("line2", result);
        Assert.Contains("line4", result);
        Assert.Contains("line5", result);
    }

    // Verifies that the generated output is deterministic for the same input.
    [Fact]
    public void Generate_IsDeterministic()
    {
        var first = CSharpGenerator.Generate(DebugJs, ReleaseJs, DefaultOutput);
        var second = CSharpGenerator.Generate(DebugJs, ReleaseJs, DefaultOutput);

        Assert.Equal(first, second);
    }

    // Verifies that each payload has its own delimiter and they do not
    // accidentally share one.
    [Fact]
    public void Generate_EachPayloadHasItsOwnDelimiter()
    {
        // The debug payload contains a triple quote run, so its delimiter
        // must be at least four quotes. The release payload has no quotes.
        var debugJs = "let x = \"\"\"end\";";
        var releaseJs = "let y = 1;";

        var result = CSharpGenerator.Generate(debugJs, releaseJs, DefaultOutput);

        // The four-quote delimiter appears for the debug payload.
        Assert.Contains(new string('"', 4), result);

        // The three-quote delimiter still appears for the release payload.
        Assert.Contains(new string('"', 3), result);
    }
}
