using TypescriptBridge.Tool;

namespace TypescriptBridge.IntegrationTests;

// Tests for CSharpGenerator, which turns a JavaScript string into a C#
// static class containing a raw string literal.
public sealed class CSharpGeneratorTests
{
    // The default output configuration used in most tests.
    private static readonly OutputConfig DefaultOutput = new();

    // Verifies that the generated class and field names appear in the output.
    [Fact]
    public void Generate_UsesConfiguredClassNameAndFieldName()
    {
        var output = new OutputConfig
        {
            ClassName = "MyProvider",
            FieldName = "MyCode",
        };

        var result = CSharpGenerator.Generate("console.log(1);", output);

        Assert.Contains("public static class MyProvider", result);
        Assert.Contains("public static readonly string MyCode =", result);
    }

    // Verifies that the auto-generated header is present.
    [Fact]
    public void Generate_EmitsAutoGeneratedHeader()
    {
        var result = CSharpGenerator.Generate("console.log(1);", DefaultOutput);

        Assert.Contains("// <auto-generated />", result);
        Assert.Contains("// This file is generated by TypescriptBridge.", result);
        Assert.Contains("// Do not edit manually.", result);
    }

    // Verifies that a simple JavaScript payload appears verbatim inside the
    // generated raw string literal.
    [Fact]
    public void Generate_IncludesJavaScriptPayload()
    {
        var js = "console.log(\"hello\");";

        var result = CSharpGenerator.Generate(js, DefaultOutput);

        Assert.Contains("console.log(\"hello\");", result);
    }

    // Verifies that a JavaScript payload containing triple quotes upgrades the
    // raw string literal delimiter to four quotes.
    [Fact]
    public void Generate_HandlesTripleQuoteInJavaScript()
    {
        var js = "let x = \"\"\"end\";";

        var result = CSharpGenerator.Generate(js, DefaultOutput);

        // The literal must start and end with at least four quotes.
        Assert.Contains("\"\"\"\"", result);
        Assert.Contains("let x = \"\"\"end\";", result);
    }

    // Verifies that a JavaScript payload containing a long run of quotes
    // upgrades the raw string literal delimiter beyond that run.
    [Fact]
    public void Generate_HandlesLongQuoteRun()
    {
        var js = "let x = \"\"\"\"\"\";";

        var result = CSharpGenerator.Generate(js, DefaultOutput);

        // The run has 5 quotes, so the delimiter must be at least 6.
        Assert.Contains(new string('"', 6), result);
        Assert.Contains(js, result);
    }

    // Verifies that an empty JavaScript payload still produces a valid class.
    [Fact]
    public void Generate_HandlesEmptyJavaScript()
    {
        var result = CSharpGenerator.Generate(string.Empty, DefaultOutput);

        Assert.Contains("public static class TypescriptProvider", result);
        Assert.Contains("public static readonly string TypescriptCode =", result);
    }

    // Verifies that CRLF line endings in the payload are normalized to LF.
    [Fact]
    public void Generate_NormalizesCrlfToLf()
    {
        var js = "line1\r\nline2\r\nline3";

        var result = CSharpGenerator.Generate(js, DefaultOutput);

        Assert.DoesNotContain("\r", result);
        Assert.Contains("line1", result);
        Assert.Contains("line2", result);
        Assert.Contains("line3", result);
    }

    // Verifies that a trailing newline in the payload does not produce an
    // extra blank line inside the raw string literal.
    [Fact]
    public void Generate_StripsTrailingNewline()
    {
        var js = "console.log(1);\n";

        var result = CSharpGenerator.Generate(js, DefaultOutput);

        // The generator emits the closing delimiter on its own line.
        // We just check that there is no visible empty line right before it.
        var lines = result.Split('\n');
        var closingIndex = Array.FindIndex(lines, line => line.TrimEnd() == "        \"\"\";");

        Assert.True(closingIndex > 0);
        Assert.NotEqual(string.Empty, lines[closingIndex - 1].TrimEnd());
    }

    // Verifies that the generated output is deterministic for the same input.
    [Fact]
    public void Generate_IsDeterministic()
    {
        var js = "console.log(1);";

        var first = CSharpGenerator.Generate(js, DefaultOutput);
        var second = CSharpGenerator.Generate(js, DefaultOutput);

        Assert.Equal(first, second);
    }
}
