using System.Text;

namespace TypescriptBridge.Tool;

// Generates a C# source file that embeds a JavaScript payload inside a
// static readonly string field.
internal static class CSharpGenerator
{
    // Produces the full C# source text for the given JavaScript payload and
    // output configuration.
    public static string Generate(string js, OutputConfig output)
    {
        var sb = new StringBuilder();

        // Emit the auto-generated header.
        // Explicit \n keeps the output deterministic across platforms.
        sb.Append("// <auto-generated />").Append('\n');
        sb.Append("// This file is generated by TypescriptBridge.").Append('\n');
        sb.Append("// Do not edit manually. Changes will be overwritten on next build.").Append('\n');
        sb.Append('\n');

        // Open the class.
        sb.Append($"public static class {output.ClassName}").Append('\n');
        sb.Append('{').Append('\n');

        // Emit the readonly field declaration.
        sb.Append($"    public static readonly string {output.FieldName} =").Append('\n');
        AppendRawStringLiteral(sb, js, indent: "        ");
        sb.Append(';').Append('\n');

        // Close the class. No trailing newline after the final brace.
        sb.Append('}');

        return sb.ToString();
    }

    // Appends a C# 11 raw string literal containing the given content.
    // The delimiter is extended if the content contains runs of quotes.
    private static void AppendRawStringLiteral(
        StringBuilder sb,
        string content,
        string indent)
    {
        // Find the longest run of consecutive double quotes in the content.
        // The delimiter must be longer than this run.
        int longestRun = 0;
        int currentRun = 0;

        foreach (var ch in content)
        {
            if (ch == '"')
            {
                currentRun++;

                if (currentRun > longestRun)
                    longestRun = currentRun;
            }
            else
            {
                currentRun = 0;
            }
        }

        int quoteCount = Math.Max(3, longestRun + 1);
        var quotes = new string('"', quoteCount);

        // Normalize all line endings to LF so the output is deterministic.
        var normalized = content
            .Replace("\r\n", "\n")
            .Replace("\r", "\n");

        // Strip a single trailing newline so the closing delimiter does not
        // sit below an empty line.
        if (normalized.EndsWith("\n"))
            normalized = normalized.Substring(0, normalized.Length - 1);

        var lines = normalized.Split('\n');

        // Opening delimiter on its own line.
        sb.Append(indent)
            .Append(quotes)
            .Append('\n');

        // Payload lines, each indented to the raw string literal level.
        foreach (var line in lines)
        {
            if (line.Length == 0)
                sb.Append('\n');
            else
                sb.Append(indent)
                    .Append(line)
                    .Append('\n');
        }

        // Closing delimiter, no trailing newline.
        sb.Append(indent)
            .Append(quotes);
    }
}
