using System.Text;

namespace TypescriptBridge.Tool;

// Generates a C# class with one field per named TypeScript bundle.
// Each field embeds Debug and Release JavaScript payloads.
// The C# compiler selects the appropriate payload at build time via
// the #if DEBUG / #else / #endif preprocessor directives.
internal sealed record GeneratedBundle(string FieldName, string DebugJavaScript, string ReleaseJavaScript);

internal static class CSharpGenerator
{
    // Preserve the single-entry API for callers using the legacy config.
    public static string Generate(
        string jsDebug,
        string jsRelease,
        OutputConfig output,
        string? rootNamespace = null)
        => Generate(new[] { new GeneratedBundle(output.FieldName, jsDebug, jsRelease) },
            output, rootNamespace);

    public static string Generate(
        IReadOnlyList<GeneratedBundle> bundles,
        OutputConfig output,
        string? rootNamespace = null)
    {
        var sb = new StringBuilder();
        sb.Append("// <auto-generated />").Append('\n');
        sb.Append("// This file is generated by TypescriptBridge.").Append('\n');
        sb.Append("// Do not edit manually. Changes will be overwritten on next build.").Append('\n');
        sb.Append('\n');

        if (!string.IsNullOrWhiteSpace(rootNamespace))
        {
            sb.Append($"namespace {rootNamespace};").Append('\n');
            sb.Append('\n');
        }

        sb.Append($"public static class {output.ClassName}").Append('\n');
        sb.Append('{').Append('\n');
        sb.Append("    // DEBUG builds use the debug payload.").Append('\n');
        sb.Append("    // RELEASE builds use the release payload.").Append('\n');

        foreach (var bundle in bundles)
        {
            sb.Append($"    public static readonly string {bundle.FieldName} =").Append('\n');
            sb.Append("#if DEBUG").Append('\n');
            AppendRawStringLiteral(sb, bundle.DebugJavaScript, indent: "        ");
            sb.Append(';').Append('\n');
            sb.Append("#else").Append('\n');
            AppendRawStringLiteral(sb, bundle.ReleaseJavaScript, indent: "        ");
            sb.Append(';').Append('\n');
            sb.Append("#endif").Append('\n');
        }

        sb.Append('}');
        return sb.ToString();
    }
    // Appends a C# 11 raw string literal containing the given content.
    // The delimiter is extended if the content contains runs of quotes.
    private static void AppendRawStringLiteral(
        StringBuilder sb,
        string content,
        string indent)
    {
        // Find the longest run of consecutive double quotes in the content.
        // The delimiter must be longer than this run.
        int longestRun = 0;
        int currentRun = 0;

        foreach (var ch in content)
        {
            if (ch == '"')
            {
                currentRun++;

                if (currentRun > longestRun)
                    longestRun = currentRun;
            }
            else
            {
                currentRun = 0;
            }
        }

        int quoteCount = Math.Max(3, longestRun + 1);
        var quotes = new string('"', quoteCount);

        // Normalize all line endings to LF so the output is deterministic.
        var normalized = content
            .Replace("\r\n", "\n")
            .Replace("\r", "\n");

        // Strip a single trailing newline so the closing delimiter does not
        // sit below an empty line.
        if (normalized.EndsWith("\n"))
            normalized = normalized.Substring(0, normalized.Length - 1);

        var lines = normalized.Split('\n');

        // Opening delimiter on its own line.
        sb.Append(indent)
            .Append(quotes)
            .Append('\n');

        // Payload lines, each indented to the raw string literal level.
        foreach (var line in lines)
        {
            if (line.Length == 0)
                sb.Append('\n');
            else
                sb.Append(indent)
                    .Append(line)
                    .Append('\n');
        }

        // Closing delimiter, no trailing newline.
        sb.Append(indent)
            .Append(quotes);
    }
}
