using System.Text;

namespace TypescriptBridge.Tool;

// Generates a C# source file that embeds two JavaScript payloads
// (debug and release) inside a single static readonly string field.
// The C# compiler selects the appropriate payload at build time via
// the #if DEBUG / #else / #endif preprocessor directives.
internal static class CSharpGenerator
{
    // Produces the full C# source text for the given debug and release
    // JavaScript payloads and output configuration.
    public static string Generate(
        string jsDebug,
        string jsRelease,
        OutputConfig output,
        string? rootNamespace = null)
    {
        var sb = new StringBuilder();

        // Emit the auto-generated header.
        // Explicit \n keeps the output deterministic across platforms.
        sb.Append("// <auto-generated />").Append('\n');
        sb.Append("// This file is generated by TypescriptBridge.").Append('\n');
        sb.Append("// Do not edit manually. Changes will be overwritten on next build.").Append('\n');
        sb.Append('\n');

        // Put the generated provider in the consuming project's namespace.
        if (!string.IsNullOrWhiteSpace(rootNamespace))
        {
            sb.Append($"namespace {rootNamespace};").Append('\n');
            sb.Append('\n');
        }

        // Open the class.
        sb.Append($"public static class {output.ClassName}").Append('\n');
        sb.Append('{').Append('\n');

        // Emit an explanatory comment inside the class.
        sb.Append("    // DEBUG builds use the debug payload.").Append('\n');
        sb.Append("    // RELEASE builds use the release payload.").Append('\n');

        // Open the field declaration.
        sb.Append($"    public static readonly string {output.FieldName} =").Append('\n');

        // Open the preprocessor block.
        sb.Append("#if DEBUG").Append('\n');

        // Emit the debug payload.
        AppendRawStringLiteral(sb, jsDebug, indent: "        ");
        sb.Append(';').Append('\n');

        // Switch to the release payload.
        sb.Append("#else").Append('\n');

        // Emit the release payload.
        AppendRawStringLiteral(sb, jsRelease, indent: "        ");
        sb.Append(';').Append('\n');

        // Close the preprocessor block.
        sb.Append("#endif").Append('\n');

        // Close the class. No trailing newline after the final brace.
        sb.Append('}');

        return sb.ToString();
    }

    // Appends a C# 11 raw string literal containing the given content.
    // The delimiter is extended if the content contains runs of quotes.
    private static void AppendRawStringLiteral(
        StringBuilder sb,
        string content,
        string indent)
    {
        // Find the longest run of consecutive double quotes in the content.
        // The delimiter must be longer than this run.
        int longestRun = 0;
        int currentRun = 0;

        foreach (var ch in content)
        {
            if (ch == '"')
            {
                currentRun++;

                if (currentRun > longestRun)
                    longestRun = currentRun;
            }
            else
            {
                currentRun = 0;
            }
        }

        int quoteCount = Math.Max(3, longestRun + 1);
        var quotes = new string('"', quoteCount);

        // Normalize all line endings to LF so the output is deterministic.
        var normalized = content
            .Replace("\r\n", "\n")
            .Replace("\r", "\n");

        // Strip a single trailing newline so the closing delimiter does not
        // sit below an empty line.
        if (normalized.EndsWith("\n"))
            normalized = normalized.Substring(0, normalized.Length - 1);

        var lines = normalized.Split('\n');

        // Opening delimiter on its own line.
        sb.Append(indent)
            .Append(quotes)
            .Append('\n');

        // Payload lines, each indented to the raw string literal level.
        foreach (var line in lines)
        {
            if (line.Length == 0)
                sb.Append('\n');
            else
                sb.Append(indent)
                    .Append(line)
                    .Append('\n');
        }

        // Closing delimiter, no trailing newline.
        sb.Append(indent)
            .Append(quotes);
    }
}
