<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>TypescriptBridge.Tool</AssemblyName>
    <RootNamespace>TypescriptBridge.Tool</RootNamespace>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <!-- Allow the test project to access internal types for testing. -->
    <InternalsVisibleTo Include="TypescriptBridge.IntegrationTests" />
  </ItemGroup>

</Project>
