using System.Text;

namespace TsHandler.Tool;

internal static class CSharpGenerator
{
    public static string Generate(string debugJs, string releaseJs)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// This file is generated by TsHandler.");
        sb.AppendLine("// Do not edit manually. Changes will be overwritten on next build.");
        sb.AppendLine();

        sb.AppendLine($"public static class {Config.GeneratedClassName}");
        sb.AppendLine("{");

        sb.AppendLine("#if DEBUG");
        sb.AppendLine($"    public static readonly string {Config.GeneratedFieldName} =");
        AppendRawStringLiteral(sb, debugJs, indent: "        ");
        sb.AppendLine(";");
        sb.AppendLine("#else");

        sb.AppendLine($"    public static readonly string {Config.GeneratedFieldName} =");
        AppendRawStringLiteral(sb, releaseJs, indent: "        ");
        sb.AppendLine(";");
        sb.AppendLine("#endif");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void AppendRawStringLiteral(StringBuilder sb, string content, string indent)
    {
        int longestRun = 0;
        int currentRun = 0;
        foreach (var ch in content)
        {
            if (ch == '"')
            {
                currentRun++;
                if (currentRun > longestRun) longestRun = currentRun;
            }
            else
            {
                currentRun = 0;
            }
        }

        int quoteCount = Math.Max(3, longestRun + 1);
        var quotes = new string('"', quoteCount);

        var normalized = content.Replace("\r\n", "\n").Replace("\r", "\n");

        if (normalized.EndsWith("\n"))
            normalized = normalized.Substring(0, normalized.Length - 1);

        var lines = normalized.Split('\n');

        sb.Append(indent).Append(quotes).AppendLine();

        foreach (var line in lines)
        {
            if (line.Length == 0)
            {
                sb.AppendLine();
            }
            else
            {
                sb.Append(indent).AppendLine(line);
            }
        }

        sb.Append(indent).Append(quotes);
    }
}